import { safeUtcDate } from '@/utils/dateUtils';
import Link from "next/link";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import SnapshotTimeline from "./SnapshotTimeline";
import SaveToRosterButton from "./SaveToRosterButton";

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const fetchCache = 'force-no-store';

type Props = {
  params: Promise<{ id: string }>;
};

async function getMixView(id: string) {
  try {
    const res = await fetch(`https://healing-milestones-api.onrender.com/api/mix-views/${id}/public`, {
      cache: 'no-store',
      headers: {
        'Accept': 'application/json',
      },
    });

    if (res.status === 410 || res.status === 404) {
      return { expired: true };
    }

    if (!res.ok) {
      console.error(`Failed to fetch mix view: ${res.status}`);
      return null;
    }

    return await res.json();
  } catch (error) {
    console.error("Error fetching mix view:", error);
    return null;
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData || viewData.expired) {
    return {
      title: "Snapshot Expired - Healing Milestones",
      description: "This Health Snapshot has expired or is no longer available.",
    };
  }

  return {
    title: `${viewData.viewName} - Healing Milestones`,
    description: `Health Snapshot generated by ${viewData.journeys?.[0]?.authorName || 'Patient'}`,
  };
}

export default async function ViewSnapshotPage({ params }: Props) {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData) {
    return notFound();
  }

  if (viewData.expired) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '2rem', textAlign: 'center' }}>
        <h1 style={{ color: 'var(--text-primary)', marginBottom: '1rem' }}>Snapshot Unavailable</h1>
        <p style={{ color: 'var(--text-secondary)', maxWidth: '400px', lineHeight: '1.6' }}>
          This Health Snapshot has expired or has been revoked by the patient for privacy reasons.
        </p>
        <Link href="/">
          <button className="download-btn" style={{ marginTop: '2rem' }}>Return to Home</button>
        </Link>
      </div>
    );
  }

  const authorName = viewData.journeys?.[0]?.authorName || "Patient";
  const expiresAt = viewData.expiresAt ? safeUtcDate(viewData.expiresAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : "Unknown";

  // Merge and sort timeline
  const milestones = (viewData.milestones || []).map((m: any) => ({ ...m, type: 'milestone' }));
  const reports = (viewData.reports || []).map((r: any) => ({ ...r, type: 'report' }));
  
  const timeline = [...milestones, ...reports].sort((a, b) => {
    const dateA = safeUtcDate(a.date || 0).getTime();
    const dateB = safeUtcDate(b.date || 0).getTime();
    return dateB - dateA; // Descending
  });

  return (
    <>
      <div className="banner">
        <div className="banner-brand">
          <Link href="/" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '1rem' }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="Logo" className="banner-logo" />
            <div className="banner-title">
              <div style={{ letterSpacing: '0.7px' }}>HEALING</div>
              <div style={{ letterSpacing: '0.2px' }}>MILESTONES</div>
            </div>
          </Link>
        </div>
        <a href="https://healingmilestones.in" target="_blank" rel="noopener noreferrer">
          <button className="download-btn">Download the App</button>
        </a>
      </div>
      
      {/* Dashboard Summary Header */}
      <div className="dashboard-top-header" style={{ backgroundColor: '#121214', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
        <div className="dashboard-header-content" style={{ maxWidth: '1400px', margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
          <div>
            <div style={{ color: 'var(--primary)', fontWeight: 'bold', letterSpacing: '1px', marginBottom: '8px', textTransform: 'uppercase', fontSize: '0.75rem' }}>
              Dashboard
            </div>
            <h1 style={{ fontSize: '1.8rem', margin: '0 0 12px 0', color: 'var(--text-primary)' }}>{viewData.viewName}</h1>
            <div className="dashboard-meta-row" style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '8px 16px', color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: '1.5' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <div style={{ width: '24px', height: '24px', flexShrink: 0, borderRadius: '50%', backgroundColor: 'var(--primary)', color: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.7rem' }}>
                  {authorName.charAt(0).toUpperCase()}
                </div>
                <span style={{ fontWeight: '500', color: 'var(--text-primary)', whiteSpace: 'nowrap' }}>{authorName}</span>
              </div>
              <span className="meta-dot" style={{ opacity: 0.5 }}>•</span>
              <span style={{ color: '#ef4444', whiteSpace: 'nowrap' }}>Expires: {expiresAt}</span>
              <span className="meta-dot" style={{ opacity: 0.5 }}>•</span>
              <span style={{ whiteSpace: 'nowrap' }}>{timeline.length} Records</span>
            </div>
          </div>
          <div style={{ alignSelf: 'center' }}>
            <SaveToRosterButton mixViewId={id} viewName={viewData.viewName} />
          </div>
        </div>
      </div>

      <main className="dashboard-main-container" style={{ maxWidth: '1400px', margin: '0 auto', position: 'relative', zIndex: 10 }}>

        
        <SnapshotTimeline timeline={timeline} expiresAt={expiresAt} biomarkerTrends={viewData.biomarkerTrends || []} />
      </main>
    </>
  );
}
