import Link from "next/link";
import { Metadata } from "next";
import { notFound } from "next/navigation";

type Props = {
  params: Promise<{ id: string }>;
};

async function getMixView(id: string) {
  try {
    const res = await fetch(`https://healing-milestones-api.onrender.com/api/mix-views/${id}/public`, {
      cache: 'no-store',
      headers: {
        'Accept': 'application/json',
      },
    });

    if (res.status === 410 || res.status === 404) {
      return { expired: true };
    }

    if (!res.ok) {
      console.error(`Failed to fetch mix view: ${res.status}`);
      return null;
    }

    return await res.json();
  } catch (error) {
    console.error("Error fetching mix view:", error);
    return null;
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData || viewData.expired) {
    return {
      title: "Snapshot Expired - Healing Milestones",
      description: "This Health Snapshot has expired or is no longer available.",
    };
  }

  return {
    title: `${viewData.viewName} - Healing Milestones`,
    description: `Health Snapshot generated by ${viewData.journeys?.[0]?.authorName || 'Patient'}`,
  };
}

export default async function ViewSnapshotPage({ params }: Props) {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData) {
    return notFound();
  }

  if (viewData.expired) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '2rem', textAlign: 'center' }}>
        <h1 style={{ color: 'var(--text-primary)', marginBottom: '1rem' }}>Snapshot Unavailable</h1>
        <p style={{ color: 'var(--text-secondary)', maxWidth: '400px', lineHeight: '1.6' }}>
          This Health Snapshot has expired or has been revoked by the patient for privacy reasons.
        </p>
        <Link href="/">
          <button className="download-btn" style={{ marginTop: '2rem' }}>Return to Home</button>
        </Link>
      </div>
    );
  }

  const authorName = viewData.journeys?.[0]?.authorName || "Patient";
  const expiresAt = viewData.expiresAt ? new Date(viewData.expiresAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : "Unknown";

  // Merge and sort timeline
  const milestones = (viewData.milestones || []).map((m: any) => ({ ...m, type: 'milestone' }));
  const reports = (viewData.reports || []).map((r: any) => ({ ...r, type: 'report' }));
  
  const timeline = [...milestones, ...reports].sort((a, b) => {
    const dateA = new Date(a.date || 0).getTime();
    const dateB = new Date(b.date || 0).getTime();
    return dateB - dateA; // Descending
  });

  return (
    <>
      <div className="banner">
        <div className="banner-brand">
          <Link href="/" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '1rem' }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="Logo" className="banner-logo" />
            <div className="banner-title">
              <div style={{ letterSpacing: '0.7px' }}>HEALING</div>
              <div style={{ letterSpacing: '0.2px' }}>MILESTONES</div>
            </div>
          </Link>
        </div>
        <a href="https://healingmilestones.in" target="_blank" rel="noopener noreferrer">
          <button className="download-btn">Download the App</button>
        </a>
      </div>
      
      {/* Immersive Hero Section */}
      <div className="story-hero-section" style={{ minHeight: '35vh' }}>
        <div className="hero-bg-blur" style={{ backgroundColor: '#1a1a1a' }}></div>
        <div className="hero-overlay" style={{ background: 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, #09090b 100%)' }}></div>
        <div className="hero-content" style={{ bottom: '20px' }}>
          <div style={{ color: 'var(--primary)', fontWeight: 'bold', letterSpacing: '1px', marginBottom: '8px', textTransform: 'uppercase', fontSize: '0.85rem' }}>
            Health Snapshot
          </div>
          <h1 className="hero-title">{viewData.viewName}</h1>
          <div className="hero-meta">
            <div className="author-badge">
              <div className="author-avatar-small placeholder">
                {authorName.charAt(0).toUpperCase()}
              </div>
              <span className="author-name">By {authorName}</span>
            </div>
            <span className="meta-dot">•</span>
            <span className="meta-date" style={{ color: '#ef4444' }}>Expires: {expiresAt}</span>
          </div>
        </div>
      </div>

      <main className="story-container">
        <div className="milestones-timeline" style={{ marginTop: '2rem', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border)', paddingBottom: '1rem' }}>
            <h2 style={{ color: 'var(--text-primary)', margin: 0 }}>
              Snapshot Timeline ({timeline.length})
            </h2>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', backgroundColor: 'rgba(255,255,255,0.05)', padding: '4px 10px', borderRadius: '12px' }}>
              Read Only
            </div>
          </div>
          
          {timeline.length > 0 ? (
            <div className="timeline-container" style={{ position: 'relative', paddingLeft: '2rem' }}>
              <div style={{ position: 'absolute', left: '11px', top: '10px', bottom: '0', width: '2px', backgroundColor: 'var(--border)' }}></div>
              
              {timeline.map((item: any) => {
                const itemDateStr = item.date
                  ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(item.date))
                  : '';
                
                if (item.type === 'milestone') {
                  return (
                    <div key={`m-${item.id}`} className="milestone-card" style={{ position: 'relative', marginBottom: '2rem' }}>
                      <div style={{ 
                        position: 'absolute', left: '-2rem', top: '6px', width: '12px', height: '12px', 
                        borderRadius: '50%', backgroundColor: 'var(--primary)', boxShadow: '0 0 10px var(--glow)'
                      }}></div>
                      <div style={{ backgroundColor: 'var(--surface)', borderRadius: '16px', padding: '1.5rem', border: '1px solid var(--border)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                          <div style={{ fontWeight: '600', color: 'var(--text-primary)' }}>Journal Update</div>
                          <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>{itemDateStr}</div>
                        </div>
                        {item.mediaUrl && (
                          <div style={{ marginBottom: '1rem', borderRadius: '12px', overflow: 'hidden' }}>
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img src={item.mediaUrl} alt="Media" style={{ width: '100%', height: 'auto', display: 'block' }} />
                          </div>
                        )}
                        {item.text && (
                          <div style={{ color: '#eaeaea', lineHeight: '1.6', whiteSpace: 'pre-wrap' }}>{item.text}</div>
                        )}
                      </div>
                    </div>
                  );
                } else if (item.type === 'report') {
                  return (
                    <div key={`r-${item.id}`} className="milestone-card" style={{ position: 'relative', marginBottom: '2rem' }}>
                      <div style={{ 
                        position: 'absolute', left: '-2rem', top: '6px', width: '12px', height: '12px', 
                        borderRadius: '50%', backgroundColor: '#3b82f6', boxShadow: '0 0 10px rgba(59,130,246,0.5)'
                      }}></div>
                      <div style={{ backgroundColor: 'var(--surface)', borderRadius: '16px', padding: '1.5rem', border: '1px solid var(--border)', borderLeft: '4px solid #3b82f6' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                          <div style={{ fontWeight: '600', color: '#3b82f6', display: 'flex', alignItems: 'center', gap: '8px' }}>
                            📄 Medical Report
                          </div>
                          <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>{itemDateStr}</div>
                        </div>
                        <h3 style={{ margin: '0 0 1rem 0', color: 'var(--text-primary)', fontSize: '1.1rem' }}>{item.title}</h3>
                        
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                          {(item.files || []).map((file: any, index: number) => {
                            const url = typeof file === 'string' ? file : file.url;
                            if (!url) return null;
                            const isPdf = url.toLowerCase().includes('.pdf');
                            const isImage = url.toLowerCase().match(/\.(jpeg|jpg|gif|png|webp)$/) != null;

                            return (
                              <div key={index} style={{ border: '1px solid rgba(255,255,255,0.05)', borderRadius: '12px', overflow: 'hidden', backgroundColor: 'rgba(0,0,0,0.2)' }}>
                                {isPdf ? (
                                  <div style={{ width: '100%', height: '400px', backgroundColor: '#fff' }}>
                                    <iframe src={`${url}#toolbar=0`} width="100%" height="100%" style={{ border: 'none' }} title={`Medical Document ${index + 1}`} />
                                  </div>
                                ) : isImage ? (
                                  // eslint-disable-next-line @next/next/no-img-element
                                  <img src={url} alt={`Medical Document ${index + 1}`} style={{ width: '100%', height: 'auto', display: 'block' }} />
                                ) : (
                                  <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>
                                    Document preview not available
                                  </div>
                                )}
                                
                                <div style={{ padding: '12px', display: 'flex', justifyContent: 'center', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
                                  <a href={url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none', width: '100%' }}>
                                    <button style={{ 
                                      width: '100%', padding: '10px', backgroundColor: 'rgba(59,130,246,0.1)', color: '#3b82f6', 
                                      border: '1px solid rgba(59,130,246,0.2)', borderRadius: '8px', fontWeight: '600', 
                                      cursor: 'pointer' 
                                    }}>
                                      {isPdf ? 'Open Full PDF' : isImage ? 'Open Full Image' : 'Download File'}
                                    </button>
                                  </a>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    </div>
                  );
                }
              })}
            </div>
          ) : (
            <div className="no-milestones" style={{ color: 'var(--text-secondary)', padding: '2rem 0' }}>
              No timeline items available in this snapshot.
            </div>
          )}
          
          <div className="interaction-prompt" style={{ marginTop: '24px', textAlign: 'center', padding: '1.5rem', backgroundColor: 'rgba(239, 68, 68, 0.05)', borderRadius: '16px', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
            <p style={{ color: 'var(--text-secondary)', margin: 0, fontSize: '0.9rem' }}>
              <strong style={{ color: 'var(--text-primary)' }}>Secure Snapshot</strong><br/>
              This view is read-only and will automatically expire and permanently self-destruct on {expiresAt}.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
