import Link from "next/link";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import SnapshotTimeline from "./SnapshotTimeline";

type Props = {
  params: Promise<{ id: string }>;
};

async function getMixView(id: string) {
  try {
    const res = await fetch(`https://healing-milestones-api.onrender.com/api/mix-views/${id}/public`, {
      cache: 'no-store',
      headers: {
        'Accept': 'application/json',
      },
    });

    if (res.status === 410 || res.status === 404) {
      return { expired: true };
    }

    if (!res.ok) {
      console.error(`Failed to fetch mix view: ${res.status}`);
      return null;
    }

    return await res.json();
  } catch (error) {
    console.error("Error fetching mix view:", error);
    return null;
  }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData || viewData.expired) {
    return {
      title: "Snapshot Expired - Healing Milestones",
      description: "This Health Snapshot has expired or is no longer available.",
    };
  }

  return {
    title: `${viewData.viewName} - Healing Milestones`,
    description: `Health Snapshot generated by ${viewData.journeys?.[0]?.authorName || 'Patient'}`,
  };
}

export default async function ViewSnapshotPage({ params }: Props) {
  const resolvedParams = await params;
  const id = resolvedParams.id;
  const viewData = await getMixView(id);

  if (!viewData) {
    return notFound();
  }

  if (viewData.expired) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '2rem', textAlign: 'center' }}>
        <h1 style={{ color: 'var(--text-primary)', marginBottom: '1rem' }}>Snapshot Unavailable</h1>
        <p style={{ color: 'var(--text-secondary)', maxWidth: '400px', lineHeight: '1.6' }}>
          This Health Snapshot has expired or has been revoked by the patient for privacy reasons.
        </p>
        <Link href="/">
          <button className="download-btn" style={{ marginTop: '2rem' }}>Return to Home</button>
        </Link>
      </div>
    );
  }

  const authorName = viewData.journeys?.[0]?.authorName || "Patient";
  const expiresAt = viewData.expiresAt ? new Date(viewData.expiresAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : "Unknown";

  // Merge and sort timeline
  const milestones = (viewData.milestones || []).map((m: any) => ({ ...m, type: 'milestone' }));
  const reports = (viewData.reports || []).map((r: any) => ({ ...r, type: 'report' }));
  
  const timeline = [...milestones, ...reports].sort((a, b) => {
    const dateA = new Date(a.date || 0).getTime();
    const dateB = new Date(b.date || 0).getTime();
    return dateB - dateA; // Descending
  });

  return (
    <>
      <div className="banner">
        <div className="banner-brand">
          <Link href="/" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '1rem' }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="Logo" className="banner-logo" />
            <div className="banner-title">
              <div style={{ letterSpacing: '0.7px' }}>HEALING</div>
              <div style={{ letterSpacing: '0.2px' }}>MILESTONES</div>
            </div>
          </Link>
        </div>
        <a href="https://healingmilestones.in" target="_blank" rel="noopener noreferrer">
          <button className="download-btn">Download the App</button>
        </a>
      </div>
      
      {/* Immersive Hero Section */}
      <div className="story-hero-section" style={{ minHeight: '35vh' }}>
        <div className="hero-bg-blur" style={{ backgroundColor: '#1a1a1a' }}></div>
        <div className="hero-overlay" style={{ background: 'linear-gradient(to bottom, rgba(0,0,0,0.3) 0%, #09090b 100%)' }}></div>
        <div className="hero-content" style={{ bottom: '20px' }}>
          <div style={{ color: 'var(--primary)', fontWeight: 'bold', letterSpacing: '1px', marginBottom: '8px', textTransform: 'uppercase', fontSize: '0.85rem' }}>
            Health Snapshot
          </div>
          <h1 className="hero-title">{viewData.viewName}</h1>
          <div className="hero-meta">
            <div className="author-badge">
              <div className="author-avatar-small placeholder">
                {authorName.charAt(0).toUpperCase()}
              </div>
              <span className="author-name">By {authorName}</span>
            </div>
            <span className="meta-dot">•</span>
            <span className="meta-date" style={{ color: '#ef4444' }}>Expires: {expiresAt}</span>
          </div>
        </div>
      </div>

      <main className="story-container">
        <SnapshotTimeline timeline={timeline} expiresAt={expiresAt} />
      </main>
    </>
  );
}
